### PR TITLE
mutualize dockerfiles for all debian versions

### PR DESCRIPTION
**Pull request by jdrouet**
This PR avoids duplication for the `bullseye` and `buster` dockerfiles.
With this variant, we end up having a folder for debian instead of a debian version, which is coherent with the alpine folder.

Question: should we change the default debian version from buster to bullseye?

Signed-off-by: Jérémie Drouet <jeremie.drouet@gmail.com>

### CODE REVIEW

**Comment by jdrouet** [comment]
Apparently reviewers are not being pinged so I'll ping @sfackler 😉

**Comment by sfackler** [comment]
Yeah, the set of images we publish here and the default tags should mirror the stable rust images.

**Comment by jdrouet** [comment]
Do you want me to do the same for the stable images?

**Comment by sfackler** [comment]
I don't believe the stable image release process through docker-library/official-images supports that setup.

**Pull request merged**
